#define UMOD_LEXEME_TYPE_Algorithm                      1
#define UMOD_LEXEME_TYPE_Discrete                       2
#define UMOD_LEXEME_TYPE_False                          3
#define UMOD_LEXEME_TYPE_Loop                           4
#define UMOD_LEXEME_TYPE_Pure                           5
#define UMOD_LEXEME_TYPE_And                            6
#define UMOD_LEXEME_TYPE_Each                           7
#define UMOD_LEXEME_TYPE_Final                          8
#define UMOD_LEXEME_TYPE_Model                          9
#define UMOD_LEXEME_TYPE_Record                         10
#define UMOD_LEXEME_TYPE_Annotation                     11
#define UMOD_LEXEME_TYPE_Else                           12
#define UMOD_LEXEME_TYPE_Flow                           13
#define UMOD_LEXEME_TYPE_Not                            14
#define UMOD_LEXEME_TYPE_Redeclare                      15
#define UMOD_LEXEME_TYPE_Assert                         16
#define UMOD_LEXEME_TYPE_Elseif                         17
#define UMOD_LEXEME_TYPE_For                            18
#define UMOD_LEXEME_TYPE_Operator                       19
#define UMOD_LEXEME_TYPE_Replaceable                    20
#define UMOD_LEXEME_TYPE_Block                          21
#define UMOD_LEXEME_TYPE_Elsewhen                       22
#define UMOD_LEXEME_TYPE_Function                       23
#define UMOD_LEXEME_TYPE_Or                             24
#define UMOD_LEXEME_TYPE_Return                         25
#define UMOD_LEXEME_TYPE_Break                          26
#define UMOD_LEXEME_TYPE_Encapsulated                   27
#define UMOD_LEXEME_TYPE_If                             28
#define UMOD_LEXEME_TYPE_Outer                          29
#define UMOD_LEXEME_TYPE_Stream                         30
#define UMOD_LEXEME_TYPE_Class                          31
#define UMOD_LEXEME_TYPE_End                            32
#define UMOD_LEXEME_TYPE_Import                         33
#define UMOD_LEXEME_TYPE_Output                         34
#define UMOD_LEXEME_TYPE_Then                           35
#define UMOD_LEXEME_TYPE_Connect                        36
#define UMOD_LEXEME_TYPE_Enumeration                    37
#define UMOD_LEXEME_TYPE_Impure                         38
#define UMOD_LEXEME_TYPE_Package                        39
#define UMOD_LEXEME_TYPE_True                           40
#define UMOD_LEXEME_TYPE_Connector                      41
#define UMOD_LEXEME_TYPE_Equation                       42
#define UMOD_LEXEME_TYPE_In                             43
#define UMOD_LEXEME_TYPE_Parameter                      44
#define UMOD_LEXEME_TYPE_Type                           45
#define UMOD_LEXEME_TYPE_Constant                       46
#define UMOD_LEXEME_TYPE_Expandable                     47
#define UMOD_LEXEME_TYPE_Initial                        48
#define UMOD_LEXEME_TYPE_Partial                        49
#define UMOD_LEXEME_TYPE_When                           50
#define UMOD_LEXEME_TYPE_Constrainedby                  51
#define UMOD_LEXEME_TYPE_Extends                        52
#define UMOD_LEXEME_TYPE_Inner                          53
#define UMOD_LEXEME_TYPE_Protected                      54
#define UMOD_LEXEME_TYPE_While                          55
#define UMOD_LEXEME_TYPE_Der                            56
#define UMOD_LEXEME_TYPE_External                       57
#define UMOD_LEXEME_TYPE_Input                          58
#define UMOD_LEXEME_TYPE_Public                         59
#define UMOD_LEXEME_TYPE_Within                         60
#define UMOD_LEXEME_TYPE_Plus                           61
#define UMOD_LEXEME_TYPE_Minus                          62
#define UMOD_LEXEME_TYPE_Mul                            63
#define UMOD_LEXEME_TYPE_Div                            64
#define UMOD_LEXEME_TYPE_Exponent                       65
#define UMOD_LEXEME_TYPE_Assign                         66
#define UMOD_LEXEME_TYPE_PlusAssign                     67
#define UMOD_LEXEME_TYPE_MinusAssign                    68
#define UMOD_LEXEME_TYPE_MulAssign                      69
#define UMOD_LEXEME_TYPE_DivAssign                      70
#define UMOD_LEXEME_TYPE_Greater                        72
#define UMOD_LEXEME_TYPE_GreaterOrEqual                 73
#define UMOD_LEXEME_TYPE_Lesser                         74
#define UMOD_LEXEME_TYPE_LesserOrEqual                  75
#define UMOD_LEXEME_TYPE_Equal                          76
#define UMOD_LEXEME_TYPE_NotEqual                       77
#define UMOD_LEXEME_TYPE_Negate                         78
#define UMOD_LEXEME_TYPE_Inv                            79
#define UMOD_LEXEME_TYPE_Incrementation                 80
#define UMOD_LEXEME_TYPE_Decrementation                 81
#define UMOD_LEXEME_TYPE_LParen                         82
#define UMOD_LEXEME_TYPE_RParen                         83
#define UMOD_LEXEME_TYPE_LBracket                       84
#define UMOD_LEXEME_TYPE_RBracket                       85
#define UMOD_LEXEME_TYPE_LBrace                         86
#define UMOD_LEXEME_TYPE_RBrace                         87
#define UMOD_LEXEME_TYPE_QuestionMark                   88
#define UMOD_LEXEME_TYPE_Dot                            89
#define UMOD_LEXEME_TYPE_Semicolon                      90
#define UMOD_LEXEME_TYPE_Colon                          91
#define UMOD_LEXEME_TYPE_Comma                          92
#define UMOD_LEXEME_TYPE_Ident                          93
#define UMOD_LEXEME_TYPE_Number                         94
#define UMOD_LEXEME_TYPE_Float                          95
#define UMOD_LEXEME_TYPE_String                         96
#define UMOD_LEXEME_TYPE_Comment                        97