#define UMOD_LEXEME_TYPE_If                              1
#define UMOD_LEXEME_TYPE_Var                             2
#define UMOD_LEXEME_TYPE_Else                            3
#define UMOD_LEXEME_TYPE_Null                            4
#define UMOD_LEXEME_TYPE_True                            5
#define UMOD_LEXEME_TYPE_False                           6
#define UMOD_LEXEME_TYPE_Return                          7
#define UMOD_LEXEME_TYPE_Function                        8
#define UMOD_LEXEME_TYPE_Undefined                       9
#define UMOD_LEXEME_TYPE_Plus                           10
#define UMOD_LEXEME_TYPE_Minus                          11
#define UMOD_LEXEME_TYPE_Mul                            12
#define UMOD_LEXEME_TYPE_Div                            13
#define UMOD_LEXEME_TYPE_Mod                            14
#define UMOD_LEXEME_TYPE_Assign                         15
#define UMOD_LEXEME_TYPE_PlusAssign                     16
#define UMOD_LEXEME_TYPE_MinusAssign                    17
#define UMOD_LEXEME_TYPE_MulAssign                      18
#define UMOD_LEXEME_TYPE_DivAssign                      19
#define UMOD_LEXEME_TYPE_ModAssign                      20
#define UMOD_LEXEME_TYPE_Greater                        21
#define UMOD_LEXEME_TYPE_GreaterOrEqual                 22
#define UMOD_LEXEME_TYPE_Lesser                         23
#define UMOD_LEXEME_TYPE_LesserOrEqual                  24
#define UMOD_LEXEME_TYPE_Equal                          25
#define UMOD_LEXEME_TYPE_NotEqual                       26
#define UMOD_LEXEME_TYPE_Not                            27
#define UMOD_LEXEME_TYPE_Inv                            28
#define UMOD_LEXEME_TYPE_Incrementation                 29
#define UMOD_LEXEME_TYPE_Decrementation                 30
#define UMOD_LEXEME_TYPE_LParen                         31
#define UMOD_LEXEME_TYPE_RParen                         32
#define UMOD_LEXEME_TYPE_LBracket                       33
#define UMOD_LEXEME_TYPE_RBracket                       34
#define UMOD_LEXEME_TYPE_LBrace                         35
#define UMOD_LEXEME_TYPE_RBrace                         36
#define UMOD_LEXEME_TYPE_QuestionMark                   37
#define UMOD_LEXEME_TYPE_Dot                            38
#define UMOD_LEXEME_TYPE_Semicolon                      39
#define UMOD_LEXEME_TYPE_Colon                          40
#define UMOD_LEXEME_TYPE_Comma                          41
#define UMOD_LEXEME_TYPE_Identifier                     42
#define UMOD_LEXEME_TYPE_Number                         43
#define UMOD_LEXEME_TYPE_String                         44
