#define UMOD_LEXEME_TYPE_ALGORITHM                      1
#define UMOD_LEXEME_TYPE_AND                            2
#define UMOD_LEXEME_TYPE_ANNOTATION                     3
#define UMOD_LEXEME_TYPE_ASSERT                         4
#define UMOD_LEXEME_TYPE_ASSIGN                         5
#define UMOD_LEXEME_TYPE_BLOCK                          6
#define UMOD_LEXEME_TYPE_BREAK                          7
#define UMOD_LEXEME_TYPE_CLASS                          8
#define UMOD_LEXEME_TYPE_COLON                          9
#define UMOD_LEXEME_TYPE_COMMA                          10
#define UMOD_LEXEME_TYPE_COMMENT                        11
#define UMOD_LEXEME_TYPE_CONNECT                        12
#define UMOD_LEXEME_TYPE_CONNECTOR                      13
#define UMOD_LEXEME_TYPE_CONSTANT                       14
#define UMOD_LEXEME_TYPE_CONSTRAINEDBY                  15
#define UMOD_LEXEME_TYPE_DECREMENTATION                 16
#define UMOD_LEXEME_TYPE_DER                            17
#define UMOD_LEXEME_TYPE_DISCRETE                       18
#define UMOD_LEXEME_TYPE_DIV                            19
#define UMOD_LEXEME_TYPE_DIVASSIGN                      20
#define UMOD_LEXEME_TYPE_DOT                            21
#define UMOD_LEXEME_TYPE_EACH                           22
#define UMOD_LEXEME_TYPE_ELSE                           23
#define UMOD_LEXEME_TYPE_ELSEIF                         24
#define UMOD_LEXEME_TYPE_ELSEWHEN                       25
#define UMOD_LEXEME_TYPE_ENCAPSULATED                   26
#define UMOD_LEXEME_TYPE_END                            27
#define UMOD_LEXEME_TYPE_ENUMERATION                    28
#define UMOD_LEXEME_TYPE_EQUAL                          29
#define UMOD_LEXEME_TYPE_EQUATION                       30
#define UMOD_LEXEME_TYPE_EXPANDABLE                     31
#define UMOD_LEXEME_TYPE_EXPONENT                       32
#define UMOD_LEXEME_TYPE_EXTENDS                        33
#define UMOD_LEXEME_TYPE_EXTERNAL                       34
#define UMOD_LEXEME_TYPE_FALSE                          35
#define UMOD_LEXEME_TYPE_FINAL                          36
#define UMOD_LEXEME_TYPE_FLOAT                          37
#define UMOD_LEXEME_TYPE_FLOW                           38
#define UMOD_LEXEME_TYPE_FOR                            39
#define UMOD_LEXEME_TYPE_FUNCTION                       40
#define UMOD_LEXEME_TYPE_GREATER                        41
#define UMOD_LEXEME_TYPE_GREATEROREQUAL                 42
#define UMOD_LEXEME_TYPE_IDENT                          43
#define UMOD_LEXEME_TYPE_IF                             44
#define UMOD_LEXEME_TYPE_IMPORT                         45
#define UMOD_LEXEME_TYPE_IMPURE                         46
#define UMOD_LEXEME_TYPE_IN                             47
#define UMOD_LEXEME_TYPE_INCREMENTATION                 48
#define UMOD_LEXEME_TYPE_INITIAL                        49
#define UMOD_LEXEME_TYPE_INNER                          50
#define UMOD_LEXEME_TYPE_INPUT                          51
#define UMOD_LEXEME_TYPE_INV                            52
#define UMOD_LEXEME_TYPE_LBRACE                         53
#define UMOD_LEXEME_TYPE_LBRACKET                       54
#define UMOD_LEXEME_TYPE_LPAREN                         55
#define UMOD_LEXEME_TYPE_LESSER                         56
#define UMOD_LEXEME_TYPE_LESSEROREQUAL                  57
#define UMOD_LEXEME_TYPE_LOOP                           58
#define UMOD_LEXEME_TYPE_MINUS                          59
#define UMOD_LEXEME_TYPE_MINUSASSIGN                    60
#define UMOD_LEXEME_TYPE_MODEL                          61
#define UMOD_LEXEME_TYPE_MUL                            62
#define UMOD_LEXEME_TYPE_MULASSIGN                      63
#define UMOD_LEXEME_TYPE_NEGATE                         64
#define UMOD_LEXEME_TYPE_NOT                            65
#define UMOD_LEXEME_TYPE_NOTEQUAL                       66
#define UMOD_LEXEME_TYPE_NUMBER                         67
#define UMOD_LEXEME_TYPE_OPERATOR                       68
#define UMOD_LEXEME_TYPE_OR                             69
#define UMOD_LEXEME_TYPE_OUTER                          70
#define UMOD_LEXEME_TYPE_OUTPUT                         71
#define UMOD_LEXEME_TYPE_PACKAGE                        72
#define UMOD_LEXEME_TYPE_PARAMETER                      73
#define UMOD_LEXEME_TYPE_PARTIAL                        74
#define UMOD_LEXEME_TYPE_PLUS                           75
#define UMOD_LEXEME_TYPE_PLUSASSIGN                     76
#define UMOD_LEXEME_TYPE_PROTECTED                      77
#define UMOD_LEXEME_TYPE_PUBLIC                         78
#define UMOD_LEXEME_TYPE_PURE                           79
#define UMOD_LEXEME_TYPE_QUESTIONMARK                   80
#define UMOD_LEXEME_TYPE_RBRACE                         81
#define UMOD_LEXEME_TYPE_RBRACKET                       82
#define UMOD_LEXEME_TYPE_RPAREN                         83
#define UMOD_LEXEME_TYPE_RECORD                         84
#define UMOD_LEXEME_TYPE_REDECLARE                      85
#define UMOD_LEXEME_TYPE_REPLACEABLE                    86
#define UMOD_LEXEME_TYPE_RETURN                         87
#define UMOD_LEXEME_TYPE_SEMICOLON                      88
#define UMOD_LEXEME_TYPE_STREAM                         89
#define UMOD_LEXEME_TYPE_STRING                         90
#define UMOD_LEXEME_TYPE_THEN                           91
#define UMOD_LEXEME_TYPE_TRUE                           92
#define UMOD_LEXEME_TYPE_TYPE                           93
#define UMOD_LEXEME_TYPE_WHEN                           94
#define UMOD_LEXEME_TYPE_WHILE                          95
#define UMOD_LEXEME_TYPE_WITHIN                         96
