UMOD_DEFINE_LEXEME(End, 0)

UMOD_AUTO_LEXEME(Spaces)
UMOD_AUTO_LEXEME(Newline)

UMOD_LEXEME(If)
UMOD_LEXEME(Var)
UMOD_LEXEME(Else)
UMOD_LEXEME(Null)
UMOD_LEXEME(True)
UMOD_LEXEME(False)
UMOD_LEXEME(Return)
UMOD_LEXEME(Function)
UMOD_LEXEME(Undefined)

UMOD_LEXEME(Plus)
UMOD_LEXEME(Minus)
UMOD_LEXEME(Mul)
UMOD_LEXEME(Div)
UMOD_LEXEME(Mod)

UMOD_LEXEME(Assign)
UMOD_LEXEME(PlusAssign)
UMOD_LEXEME(MinusAssign)
UMOD_LEXEME(MulAssign)
UMOD_LEXEME(DivAssign)
UMOD_LEXEME(ModAssign)

UMOD_LEXEME(Greater)
UMOD_LEXEME(GreaterOrEqual)
UMOD_LEXEME(Lesser)
UMOD_LEXEME(LesserOrEqual)
UMOD_LEXEME(Equal)
UMOD_LEXEME(NotEqual)

UMOD_LEXEME(Not)
UMOD_LEXEME(Inv)
UMOD_LEXEME(Incrementation)
UMOD_LEXEME(Decrementation)

UMOD_LEXEME(LParen)
UMOD_LEXEME(RParen)
UMOD_LEXEME(LBracket)
UMOD_LEXEME(RBracket)
UMOD_LEXEME(LBrace)
UMOD_LEXEME(RBrace)

UMOD_LEXEME(QuestionMark)
UMOD_LEXEME(Dot)

UMOD_LEXEME(Semicolon)
UMOD_LEXEME(Colon)
UMOD_LEXEME(Comma)

UMOD_LEXEME(Identifier)

UMOD_LEXEME(Number)
UMOD_LEXEME(String)
