#define UMOD_LEXEME_TYPE_PLUS                            1
#define UMOD_LEXEME_TYPE_MINUS                           2
#define UMOD_LEXEME_TYPE_MUL                             3
#define UMOD_LEXEME_TYPE_DIV                             4
#define UMOD_LEXEME_TYPE_ASSIGN                          5
#define UMOD_LEXEME_TYPE_PLUSASSIGN                      6
#define UMOD_LEXEME_TYPE_MINUSASSIGN                     7
#define UMOD_LEXEME_TYPE_MULASSIGN                       8
#define UMOD_LEXEME_TYPE_DIVASSIGN                       9
#define UMOD_LEXEME_TYPE_GREATER                        10
#define UMOD_LEXEME_TYPE_GREATEROREQUAL                 11
#define UMOD_LEXEME_TYPE_LESSER                         12
#define UMOD_LEXEME_TYPE_LESSEROREQUAL                  13
#define UMOD_LEXEME_TYPE_EQUAL                          14
#define UMOD_LEXEME_TYPE_NOTEQUAL                       15
#define UMOD_LEXEME_TYPE_NOT                            16
#define UMOD_LEXEME_TYPE_INV                            17
#define UMOD_LEXEME_TYPE_INCREMENTATION                 18
#define UMOD_LEXEME_TYPE_DECREMENTATION                 19
#define UMOD_LEXEME_TYPE_LPAREN                         20
#define UMOD_LEXEME_TYPE_RPAREN                         21
#define UMOD_LEXEME_TYPE_LBRACKET                       22
#define UMOD_LEXEME_TYPE_RBRACKET                       23
#define UMOD_LEXEME_TYPE_LBRACE                         24
#define UMOD_LEXEME_TYPE_RBRACE                         25
#define UMOD_LEXEME_TYPE_SEMICOLON                      26
#define UMOD_LEXEME_TYPE_COLON                          27
#define UMOD_LEXEME_TYPE_COMMA                          28
#define UMOD_LEXEME_TYPE_IDENT                          29
#define UMOD_LEXEME_TYPE_NUMBER                         30
#define UMOD_LEXEME_TYPE_FLOAT                          31
#define UMOD_LEXEME_TYPE_STRING                         32
#define UMOD_LEXEME_TYPE_COMMENT                        33
#define UMOD_LEXEME_TYPE_QUESTIONMARK                   34
#define UMOD_LEXEME_TYPE_DOT                            35
#define UMOD_LEXEME_TYPE_ALGORITHM                      36
#define UMOD_LEXEME_TYPE_AND                            37
#define UMOD_LEXEME_TYPE_ANNOTATION                     38
#define UMOD_LEXEME_TYPE_ASSERT                         39
#define UMOD_LEXEME_TYPE_BLOCK                          40
#define UMOD_LEXEME_TYPE_BREAK                          41
#define UMOD_LEXEME_TYPE_CLASS                          42
#define UMOD_LEXEME_TYPE_CONNECT                        43
#define UMOD_LEXEME_TYPE_CONNECTOR                      44
#define UMOD_LEXEME_TYPE_CONSTANT                       45
#define UMOD_LEXEME_TYPE_CONSTRAINEDBY                  46
#define UMOD_LEXEME_TYPE_DER                            47
#define UMOD_LEXEME_TYPE_DISCRETE                       48
#define UMOD_LEXEME_TYPE_EACH                           49
#define UMOD_LEXEME_TYPE_ELSE                           50
#define UMOD_LEXEME_TYPE_ELSEIF                         51
#define UMOD_LEXEME_TYPE_ELSEWHEN                       52
#define UMOD_LEXEME_TYPE_ENCAPSULATED                   53
#define UMOD_LEXEME_TYPE_END                            54
#define UMOD_LEXEME_TYPE_ENUMERATION                    55
#define UMOD_LEXEME_TYPE_EQUATION                       56
#define UMOD_LEXEME_TYPE_EXPANDABLE                     57
#define UMOD_LEXEME_TYPE_EXPONENT                       58
#define UMOD_LEXEME_TYPE_EXTENDS                        59
#define UMOD_LEXEME_TYPE_EXTERNAL                       60
#define UMOD_LEXEME_TYPE_FALSE                          61
#define UMOD_LEXEME_TYPE_FINAL                          62
#define UMOD_LEXEME_TYPE_FLOW                           63
#define UMOD_LEXEME_TYPE_FOR                            64
#define UMOD_LEXEME_TYPE_FUNCTION                       65
#define UMOD_LEXEME_TYPE_IF                             66
#define UMOD_LEXEME_TYPE_IMPORT                         67
#define UMOD_LEXEME_TYPE_IMPURE                         68
#define UMOD_LEXEME_TYPE_IN                             69
#define UMOD_LEXEME_TYPE_INITIAL                        70
#define UMOD_LEXEME_TYPE_INNER                          71
#define UMOD_LEXEME_TYPE_INPUT                          72
#define UMOD_LEXEME_TYPE_LOOP                           73
#define UMOD_LEXEME_TYPE_MODEL                          74
#define UMOD_LEXEME_TYPE_NEGATE                         75
#define UMOD_LEXEME_TYPE_OPERATOR                       76
#define UMOD_LEXEME_TYPE_OR                             77
#define UMOD_LEXEME_TYPE_OUTER                          78
#define UMOD_LEXEME_TYPE_OUTPUT                         79
#define UMOD_LEXEME_TYPE_PACKAGE                        80
#define UMOD_LEXEME_TYPE_PARAMETER                      81
#define UMOD_LEXEME_TYPE_PARTIAL                        82
#define UMOD_LEXEME_TYPE_PROTECTED                      83
#define UMOD_LEXEME_TYPE_PUBLIC                         84
#define UMOD_LEXEME_TYPE_PURE                           85
#define UMOD_LEXEME_TYPE_RECORD                         86
#define UMOD_LEXEME_TYPE_REDECLARE                      87
#define UMOD_LEXEME_TYPE_REPLACEABLE                    88
#define UMOD_LEXEME_TYPE_RETURN                         89
#define UMOD_LEXEME_TYPE_STREAM                         90
#define UMOD_LEXEME_TYPE_THEN                           91
#define UMOD_LEXEME_TYPE_TRUE                           92
#define UMOD_LEXEME_TYPE_TYPE                           93
#define UMOD_LEXEME_TYPE_WHEN                           94
#define UMOD_LEXEME_TYPE_WHILE                          95
#define UMOD_LEXEME_TYPE_WITHIN                         96
#define UMOD_LEXEME_TYPE_NEWLINE                        97
