#define UMOD_LEXEME_TYPE_OR                              1
#define UMOD_LEXEME_TYPE_AND                             2
#define UMOD_LEXEME_TYPE_NOT                             3
#define UMOD_LEXEME_TYPE_REL_OP                          4
#define UMOD_LEXEME_TYPE_ADD_OP_PARTIAL                  5
#define UMOD_LEXEME_TYPE_PLUS                            6
#define UMOD_LEXEME_TYPE_MUL_OP_PARTIAL                  7
#define UMOD_LEXEME_TYPE_DOT_STAR                        8
#define UMOD_LEXEME_TYPE_EXP_OP                          9
#define UMOD_LEXEME_TYPE_WITHIN                         10
#define UMOD_LEXEME_TYPE_SEMICOLON                      11
#define UMOD_LEXEME_TYPE_CLASS                          12
#define UMOD_LEXEME_TYPE_MODEL                          13
#define UMOD_LEXEME_TYPE_RECORD                         14
#define UMOD_LEXEME_TYPE_BLOCK                          15
#define UMOD_LEXEME_TYPE_CONNECTOR                      16
#define UMOD_LEXEME_TYPE_TYPE                           17
#define UMOD_LEXEME_TYPE_PACKAGE                        18
#define UMOD_LEXEME_TYPE_FUNCTION                       19
#define UMOD_LEXEME_TYPE_OPERATOR_FUNCTION              20
#define UMOD_LEXEME_TYPE_OPERATOR                       21
#define UMOD_LEXEME_TYPE_PURE                           22
#define UMOD_LEXEME_TYPE_IMPURE                         23
#define UMOD_LEXEME_TYPE_IDENT                          24
#define UMOD_LEXEME_TYPE_EQUAL                          25
#define UMOD_LEXEME_TYPE_DER                            26
#define UMOD_LEXEME_TYPE_OPAREN                         27
#define UMOD_LEXEME_TYPE_COMMA                          28
#define UMOD_LEXEME_TYPE_CPAREN                         29
#define UMOD_LEXEME_TYPE_EXTENDS                        30
#define UMOD_LEXEME_TYPE_ENUMERATION                    31
#define UMOD_LEXEME_TYPE_END_IDENT                      32
#define UMOD_LEXEME_TYPE_COLON                          33
#define UMOD_LEXEME_TYPE_REPLACEABLE                    34
#define UMOD_LEXEME_TYPE_IMPORT                         35
#define UMOD_LEXEME_TYPE_DOT                            36
#define UMOD_LEXEME_TYPE_STAR                           37
#define UMOD_LEXEME_TYPE_OBRACE                         38
#define UMOD_LEXEME_TYPE_CBRACE                         39
#define UMOD_LEXEME_TYPE_PUBLIC                         40
#define UMOD_LEXEME_TYPE_PROTECTED                      41
#define UMOD_LEXEME_TYPE_EXTERNAL                       42
#define UMOD_LEXEME_TYPE_STRING                         43
#define UMOD_LEXEME_TYPE_CONSTRAINEDBY                  44
#define UMOD_LEXEME_TYPE_FLOW                           45
#define UMOD_LEXEME_TYPE_STREAM                         46
#define UMOD_LEXEME_TYPE_DISCRETE                       47
#define UMOD_LEXEME_TYPE_PARAMETER                      48
#define UMOD_LEXEME_TYPE_CONSTANT                       49
#define UMOD_LEXEME_TYPE_INPUT                          50
#define UMOD_LEXEME_TYPE_OUTPUT                         51
#define UMOD_LEXEME_TYPE_IF                             52
#define UMOD_LEXEME_TYPE_ASSIGN_OP                      53
#define UMOD_LEXEME_TYPE_REDECLARE                      54
#define UMOD_LEXEME_TYPE_INITIAL_EQUATION               55
#define UMOD_LEXEME_TYPE_EQUATION                       56
#define UMOD_LEXEME_TYPE_INITIAL_ALGORITHM              57
#define UMOD_LEXEME_TYPE_ALGORITHM                      58
#define UMOD_LEXEME_TYPE_BREAK                          59
#define UMOD_LEXEME_TYPE_RETURN                         60
#define UMOD_LEXEME_TYPE_THEN                           61
#define UMOD_LEXEME_TYPE_END_IF                         62
#define UMOD_LEXEME_TYPE_ELSEIF                         63
#define UMOD_LEXEME_TYPE_ELSE                           64
#define UMOD_LEXEME_TYPE_FOR                            65
#define UMOD_LEXEME_TYPE_LOOP                           66
#define UMOD_LEXEME_TYPE_END_FOR                        67
#define UMOD_LEXEME_TYPE_IN                             68
#define UMOD_LEXEME_TYPE_WHILE                          69
#define UMOD_LEXEME_TYPE_END_WHILE                      70
#define UMOD_LEXEME_TYPE_WHEN                           71
#define UMOD_LEXEME_TYPE_END_WHEN                       72
#define UMOD_LEXEME_TYPE_ELSEWHEN                       73
#define UMOD_LEXEME_TYPE_CONNECT                        74
#define UMOD_LEXEME_TYPE_UNSIGNED_NUMBER                75
#define UMOD_LEXEME_TYPE_OBRACKET                       76
#define UMOD_LEXEME_TYPE_CBRACKET                       77
#define UMOD_LEXEME_TYPE_END                            78
#define UMOD_LEXEME_TYPE_TRUE                           79
#define UMOD_LEXEME_TYPE_FALSE                          80
#define UMOD_LEXEME_TYPE_INITIAL                        81
#define UMOD_LEXEME_TYPE_ANNOTATION                     82
#define UMOD_LEXEME_TYPE_EACH                           83
#define UMOD_LEXEME_TYPE_ENCAPSULATED                   84
#define UMOD_LEXEME_TYPE_EXPANDABLE                     85
#define UMOD_LEXEME_TYPE_INNER                          86
#define UMOD_LEXEME_TYPE_FINAL                          87
#define UMOD_LEXEME_TYPE_OUTER                          88
#define UMOD_LEXEME_TYPE_PARTIAL                        89
