#define UMOD_LEXEME_TYPE_ASSING                          1
#define UMOD_LEXEME_TYPE_EQUAL                           2
#define UMOD_LEXEME_TYPE_THEN                            3
#define UMOD_LEXEME_TYPE_ELSE                            4
#define UMOD_LEXEME_TYPE_COLON                           5
#define UMOD_LEXEME_TYPE_NOT                             6
#define UMOD_LEXEME_TYPE_AND                             7
#define UMOD_LEXEME_TYPE_OR                              8
#define UMOD_LEXEME_TYPE_LOWER                           9
#define UMOD_LEXEME_TYPE_GREATER                        10
#define UMOD_LEXEME_TYPE_LOWEREQ                        11
#define UMOD_LEXEME_TYPE_GREATEREQ                      12
#define UMOD_LEXEME_TYPE_COMPEQ                         13
#define UMOD_LEXEME_TYPE_COMPNE                         14
#define UMOD_LEXEME_TYPE_PLUS                           15
#define UMOD_LEXEME_TYPE_DOTPLUS                        16
#define UMOD_LEXEME_TYPE_MINUS                          17
#define UMOD_LEXEME_TYPE_DOTMINUS                       18
#define UMOD_LEXEME_TYPE_UMINUS                         19
#define UMOD_LEXEME_TYPE_UPLUS                          20
#define UMOD_LEXEME_TYPE_SLASH                          21
#define UMOD_LEXEME_TYPE_DOTSLASH                       22
#define UMOD_LEXEME_TYPE_STAR                           23
#define UMOD_LEXEME_TYPE_DOTSTAR                        24
#define UMOD_LEXEME_TYPE_CARET                          25
#define UMOD_LEXEME_TYPE_DOTCARET                       26
#define UMOD_LEXEME_TYPE_FC                             27
#define UMOD_LEXEME_TYPE_PARENS                         28
#define UMOD_LEXEME_TYPE_SEMICOLON                      29
#define UMOD_LEXEME_TYPE_COMMA                          30
#define UMOD_LEXEME_TYPE_OBRACE                         31
#define UMOD_LEXEME_TYPE_OBRACKET                       32
#define UMOD_LEXEME_TYPE_OPAREN                         33
#define UMOD_LEXEME_TYPE_CBRACE                         34
#define UMOD_LEXEME_TYPE_CBRACKET                       35
#define UMOD_LEXEME_TYPE_CPAREN                         36
#define UMOD_LEXEME_TYPE_IDENT                          37
#define UMOD_LEXEME_TYPE_STRING                         38
#define UMOD_LEXEME_TYPE_WITHIN                         39
#define UMOD_LEXEME_TYPE_DOT                            40
#define UMOD_LEXEME_TYPE_ENCAPSULATED                   41
#define UMOD_LEXEME_TYPE_EXPANDABLE                     42
#define UMOD_LEXEME_TYPE_PURE                           43
#define UMOD_LEXEME_TYPE_IMPURE                         44
#define UMOD_LEXEME_TYPE_FINAL                          45
#define UMOD_LEXEME_TYPE_CLASS                          46
#define UMOD_LEXEME_TYPE_MODEL                          47
#define UMOD_LEXEME_TYPE_RECORD                         48
#define UMOD_LEXEME_TYPE_BLOCK                          49
#define UMOD_LEXEME_TYPE_CONNECTOR                      50
#define UMOD_LEXEME_TYPE_TYPE                           51
#define UMOD_LEXEME_TYPE_PACKAGE                        52
#define UMOD_LEXEME_TYPE_FUNCTION                       53
#define UMOD_LEXEME_TYPE_OPERATOR                       54
#define UMOD_LEXEME_TYPE_PARTIAL                        55
#define UMOD_LEXEME_TYPE_END                            56
#define UMOD_LEXEME_TYPE_ENUMERATION                    57
#define UMOD_LEXEME_TYPE_DER                            58
#define UMOD_LEXEME_TYPE_COMA                           59
#define UMOD_LEXEME_TYPE_EXTENDS                        60
#define UMOD_LEXEME_TYPE_EXTERNAL                       61
#define UMOD_LEXEME_TYPE_IMPORT                         62
#define UMOD_LEXEME_TYPE_REDECLARE                      63
#define UMOD_LEXEME_TYPE_INNER                          64
#define UMOD_LEXEME_TYPE_OUTER                          65
#define UMOD_LEXEME_TYPE_CONSTRAINEDBY                  66
#define UMOD_LEXEME_TYPE_REPLACABLE                     67
#define UMOD_LEXEME_TYPE_FLOW                           68
#define UMOD_LEXEME_TYPE_STREAM                         69
#define UMOD_LEXEME_TYPE_DISCRETE                       70
#define UMOD_LEXEME_TYPE_PARAMETER                      71
#define UMOD_LEXEME_TYPE_CONSTANT                       72
#define UMOD_LEXEME_TYPE_INPUT                          73
#define UMOD_LEXEME_TYPE_OUTPUT                         74
#define UMOD_LEXEME_TYPE_IF                             75
#define UMOD_LEXEME_TYPE_PUBLIC                         76
#define UMOD_LEXEME_TYPE_PROTECTED                      77
#define UMOD_LEXEME_TYPE_EACH                           78
#define UMOD_LEXEME_TYPE_REPLACEABLE                    79
#define UMOD_LEXEME_TYPE_ANNOTATION                     80
#define UMOD_LEXEME_TYPE_INITIALEQ                      81
#define UMOD_LEXEME_TYPE_EQUATION                       82
#define UMOD_LEXEME_TYPE_INITIALALG                     83
#define UMOD_LEXEME_TYPE_ALGORITHM                      84
#define UMOD_LEXEME_TYPE_IN                             85
#define UMOD_LEXEME_TYPE_FOR                            86
#define UMOD_LEXEME_TYPE_LOOP                           87
#define UMOD_LEXEME_TYPE_WHEN                           88
#define UMOD_LEXEME_TYPE_ELSEWHEN                       89
#define UMOD_LEXEME_TYPE_ELSEIF                         90
#define UMOD_LEXEME_TYPE_CONNECT                        91
#define UMOD_LEXEME_TYPE_BREAK                          92
#define UMOD_LEXEME_TYPE_RETURN                         93
#define UMOD_LEXEME_TYPE_WHILE                          94
#define UMOD_LEXEME_TYPE_INT                            95
#define UMOD_LEXEME_TYPE_FLOAT                          96
#define UMOD_LEXEME_TYPE_FALSE                          97
#define UMOD_LEXEME_TYPE_TRUE                           98
#define UMOD_LEXEME_TYPE_INITIAL                        99
#define UMOD_LEXEME_TYPE_ENDSUB                         100
